/* Auto-generated by cbindgen. Do not edit. */

#ifndef SCREENSHOTTOOL_H
#define SCREENSHOTTOOL_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Raw pixel data received from the native capture layer
 */
typedef struct SSTPixelData {
    const uint8_t *pixels;
    uint32_t width;
    uint32_t height;
    uint32_t stride;
} SSTPixelData;

/**
 * Capture callback — native app provides this so MCP/HTTP API can request captures
 */
typedef struct SSTPixelData (*SSTCaptureCallback)(uint32_t, uint32_t, uint32_t, uint32_t);

/**
 * Screenshot result passed across FFI boundary
 */
typedef struct SSTScreenshotResult {
    uint8_t *image_data;
    uintptr_t image_len;
    char *file_path;
    char *error;
} SSTScreenshotResult;

/**
 * Diff result
 */
typedef struct SSTDiffResult {
    uint8_t *image_data;
    uintptr_t image_len;
    char *file_path;
    float change_percentage;
    char *error;
} SSTDiffResult;

/**
 * Initialize the core library (call once at app startup)
 */
bool sst_init(const char *config_json);

/**
 * Shutdown the core library
 */
void sst_shutdown(void);

/**
 * Register the native capture function
 */
void sst_register_capture_callback(SSTCaptureCallback callback);

/**
 * Process a screenshot captured by the native layer
 */
struct SSTScreenshotResult sst_process_screenshot(struct SSTPixelData pixels);

/**
 * Start a new GIF recording session
 */
char *sst_gif_start(void);

/**
 * Add a frame to the active GIF recording
 */
bool sst_gif_add_frame(const char *session_id, struct SSTPixelData pixels);

/**
 * Stop GIF recording and encode all collected frames
 */
struct SSTScreenshotResult sst_gif_finish(const char *session_id);

/**
 * Store a "before" image for diff comparison
 */
bool sst_diff_store_before(struct SSTPixelData pixels);

/**
 * Compare "after" image against stored "before" and generate diff
 */
struct SSTDiffResult sst_diff_compare(struct SSTPixelData pixels);

/**
 * Get latest processed screenshot as PNG bytes
 */
struct SSTScreenshotResult sst_get_latest(void);

/**
 * Get connected companion devices as JSON string
 */
char *sst_list_companions(void);

/**
 * Request screenshot from a companion device
 */
struct SSTScreenshotResult sst_companion_screenshot(const char *device_id);

/**
 * Free memory allocated by the core library for screenshot results
 */
void sst_free_result(struct SSTScreenshotResult result);

/**
 * Free memory allocated by the core library for diff results
 */
void sst_free_diff_result(struct SSTDiffResult result);

/**
 * Free a string allocated by the core library
 */
void sst_free_string(char *s);

#endif /* SCREENSHOTTOOL_H */
